stages:
    - build
    - test
    - deploy
    

before_script:
    - npm install -g


build:
    stage: build
    tags:
        - build
        
    script:
        - echo "Building"
        - npm run build
        
test:
    stage: test
    script:
        - echo "Testing"
        - ls -a
        - npm test

deploy:
    stage: deploy
    script: 
        - npm install -g serve
        - serve -s build