stages:
    - build
    - test
    - deploy
    
build:
    stage: build
    script:
        - echo "Building"
        - mkdir build
        - touch build/info.txt
        
test:
    stage: test
    script:
        - echo "Testing"
        - ls -a
        - test -f "build/info.txt