stages:
    - test
    - build
    - deploy
    
cache:
    paths:
        - node_modules/
        - build

before_script:
    - npm install 


install_depencies:
    stage: build
    tags:
        - build
    script:
        - echo "Building"
        - npm run build
        
test:
    stage: test
    script:
        - echo "Testing"
        - ls -a
        - npm test

deploy:
    stage: deploy
    script: 
        - echo "Deploy to staging."
       # - npm install -g serve
       # - serve -s build
    environment:
        name: staging
        url: https://gc.data-input.com
