stages:
    - build
    - test
    - deploy
    
cache:
    paths:
        - node_modules/
        - build

before_script:
    - npm install 


install_depencies:
    stage: build
    tags:
        - build
    script:
        - echo "Building"
        - npm run build
        
test:
    stage: test
    script:
        - echo "Testing"
        - ls -a
        - npm test

deploy:
    stage: deploy
    script: 
        - npm install -g serve
        - serve -s build