stages:
    - build
    - test
    - deploy
    
build:
    stage: build
    tags:
        - build
        
    script:
        - echo "Building"
        - mkdir build
        - npm install
        - npm start
        - touch build/info.txt
        
test:
    stage: test
    script:
        - echo "Testing"
        - ls -a
        - npm test
